databases:
  - name: dbRender
    plan: free
    databaseName: dbRender
    user: userRender

services:
  - type: web
    plan: free
    name: deployRender
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn deployRender.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dbRender
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4